#!/bin/bash

## Copyright (c) 2018 faraco <skelic3 at gmail dot com>

GITURL="$1"

test -z "$GITURL" \
        && printf "\nUsage: cigithub <URL>" >&2 \
        && printf "\nExample: cigithub https://github.com/Skylisp/cigithub\n\n" >&2 \
        && exit 1

if [[ "$GITURL" = https?://(www.)? ]];then
        CTEMPDIR="cigithub-repo-$RANDOM"
         
        printf "* cloning $GITURL to $CTEMPDIR...\n"
        git clone "$GITURL" "$CTEMPDIR" &> /dev/null
        test $? -ne 0 \
                && printf "\n* error: failed to clone repository. Please ensure URL is valid.\n\n" >&2 \
                && exit 1

        cd $CTEMPDIR || exit

        printf "* installing egg to $CHICKEN_REPOSITORY..\n"
        chicken-install $(ls | grep ".*setup$") &> /dev/null
        test $? -ne 0 \
                && printf "\n* error: failed to install egg. Please ensure egg_name.setup exists in the directory\n\n" >&2 \
                && exit 1

        cd ..
        rm -rf $CTEMPDIR || exit

        printf "\ninstallation successful\n\n"
        exit 0

elif [[ "$GITURL" != http* ]];then
        printf "\nArgument must be a valid http(s) URL\n\n" >&2 \
        exit 1
fi
